### ISSUE TITLE
edge bidder crash

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_exploration#46]
@Jailander 

```
genpy.Duration[17925555203], 'prob': 0.0}, {'edge_id': 'HospMeetingPod3_HospActRec3', 'probs': 0.5, 'score': 1.0, 'entropy': 1.0, 'samp
les': 1, 'time': genpy.Duration[16472372797], 'prob': 0.0}, {'edge_id': 'KitchenPod3_KitchenPod2', 'probs': 0.5, 'score': 0.0, 'entropy
': 0.0, 'samples': 2, 'time': genpy.Duration[3671125875], 'prob': 0.0}, {'edge_id': 'KitchenPod3_KitchenTableLow', 'probs': 0.5, 'score
': 1.0, 'entropy': 1.0, 'samples': 0, 'time': genpy.Duration[43461990862], 'prob': 0.0}, {'edge_id': 'KitchenPod3_KitchenActRec2', 'pro
bs': 0.5, 'score': 1.0, 'entropy': 1.0, 'samples': 0, 'time': genpy.Duration[17836344071], 'prob': 0.0}]                               
Exception in thread Thread-9:                                                                                                          
Traceback (most recent call last):                                                                                                     
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                                                               
    self.run()                                                                                                                         
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/timer.py", line 223, in run                                                  
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))                                
  File "/home/strands/tsc_y4_ws/src/strands_exploration/edge_exploration/scripts/edge_bidder.py", line 50, in get_exploration_task_cb  
    self.get_exploration_task()                                                                                                        
  File "/home/strands/tsc_y4_ws/src/strands_exploration/edge_exploration/scripts/edge_bidder.py", line 93, in get_exploration_task     
    tokens_to_use= np.ceil(myd[slot])                                                                                                  
IndexError: index out of bounds                                                                                                        

[INFO] [WallTime: 1482223813.656798] Trying to add tasks to the schedule...                                                            
[INFO] [WallTime: 1482310213.663316] Trying to add tasks to the schedule...  
```

And after this is stopped working. This was yesterday in the morning.

**Comment by Jailander** [comment]
Hi that is funny :/ Im on holidays but ill try to take a look later today
